apiVersion: v1
kind: Secret
metadata:
  name: streamify-secrets
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9tYW5oZHVuZzA1MDcyMDA1Om1hbmhkdW5nMTIzMTIzQHN0cmVhbWlmeS5sYzQ5Y3VtLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1zdHJlYW1pZnk="
  STEAM_API_KEY: "cmp6NjdrYnRiMnR6"
  STEAM_API_SECRET: "dnZ2MmpjYWo0end3ZjZ4anNxOWs2azY3Z2h5Z3BrY3VncWhodHlocmZweGtneDNwZWhjeThlN3h4a3JocTR4dw=="
  JWT_SECRET_KEY: "bmd1eWVuX21hbmhfZHVuZ18wNTA3MjAwNQ=="